### ISSUE TITLE
Modifying secure_accuracy affects neighbor search/causes failure in mpi gofmm

### ISSUE THREAD

**Issue by stharakan** [ChenhanYu/hmlp#36]
I get a bug when secure_accuracy from gofmm.hpp is set to true, but everything runs ok if it is set to false. Is there any way to set it to true in distributed memory? 

Overview: 
I'm running GoFMM on a 47236 x 47236 matrix stored in double precision which is stored on scratch on stampede2. For now, I'm just trying to load it, compress, and evaluate the accuracy. I ran this on skx-dev on stampede2, on 1 node, with 1 task, and omp threads set to 48. 

Sbatch file is here (uploaded as txt for github): 
[sbatch_gofmm_userdefine.txt](https://github.com/ChenhanYu/hmlp/files/2806493/sbatch_gofmm_userdefine.txt)

The secure_accuracy flag I'm referencing is set here (https://github.com/ChenhanYu/hmlp/blob/develop/gofmm/gofmm.hpp#L192)

When it is compiled as false, there are no errors, although the error is large. Here is the output: 
[mpi_without_sa.txt](https://github.com/ChenhanYu/hmlp/files/2806501/mpi_without_sa.txt)

When compiled as true, there are errors in S2SReduceTask: 
[mpi_with_sa.txt](https://github.com/ChenhanYu/hmlp/files/2806503/mpi_with_sa.txt)

The error message is

Assertion `num_arrived_subtasks == subtasks.size()' failed.

**Comment by ChenhanYu** [comment]
Thank you for reporting this bug. 

This bug is known (or should better be addressed as lacking of functionality). Currently "secure_accruacy" only works properly on the shared memory GOFMM. If you want to see if GOFMM compress your matrix, you can give the shared memory GOFMM a try first. I will try to carry out the distributed implementation asap. 

On the other hand, "secure_accuracy" only affect the "compression" and "evaluation" (the MATVEC). This option should have no effect on the nearest neighbor search in both shared and distributed memory.  
If approximated all nearest neighbor is all you need, you check out the example to see how to perform the neighbor search only.

### Root cause
Currently "secure_accruacy" (a.k.a level-restriction) only works properly on the shared memory GOFMM. The distributed version has yet to be implemented. 
### Fix
TBD

**Comment by stharakan** [comment]
Ah, I see the that now, my bad! Thanks for the quick and detailed response. 

I'm moving back to using shared memory for now, but if I can document/recreate the nearest neighbor issue I saw on one run I will make sure to add it here.

**Comment by ChenhanYu** [comment]
No problem. Thank you for your inputs. The progress of this issue will be updated here.

**Comment by ChenhanYu** [comment]
secure_accuracy now works correctly on both shared and distributed GOFMM. You can set this option in CommandLineHelper. This option will be propagated to the other scripts in the following update. If you find any issue later, please don't hesitate to let me know.

**Comment by ChenhanYu** [comment]
The issue has been fixed. Verify to close.
